---

- name: 1Password installation tasks
  become: true
  block:
    - name: Ensure the /opt/1Password directory exists
      ansible.builtin.file:
        path: /opt/1Password
        state: directory

    - name: Get 1password for arm64
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/tar/stable/aarch64/1password-latest.tar.gz
        dest: /tmp
    
    - name: Ensure files are untarred
      ansible.builtin.unarchive:
        src: /tmp/1password-latest.tar.gz
        dest: /tmp

    - name: Ensure files are moved to /opt/1Password and install is ran
      ansible.builtin.shell: |
        mv /tmp/1password-*/* /opt/1Password
        /opt/1Password/after-install.sh
      args:
        chdir: /opt/1Password/
        creates: 1password
      register: install_1password_app

    - name: Ensure 1Password CLI for Arm64 is installed
      ansible.builtin.get_url:
        url: https://downloads.1password.com/linux/debian/arm64/stable/1password-cli-arm64-latest.deb
        dest: /tmp

    - name: Install 1password-cli
      ansible.builtin.apt:
        deb: /tmp/1password-cli-arm64-latest.deb
      register: install_1password_cli

    - name: Ensure tmp files are removed
      ansible.builtin.shell: rm -rf /tmp/1password-*
      when:
        - not install_1password_app.failed
        - not install_1password_cli.failed

    - name: Ensure app shortcut for 1password exists
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Type=Application
          Terminal=false
          Name=1Password
          Icon=/opt/1Password/resources/icons/hicolor/512x512/apps/1password.png
          Exec=/usr/bin/1password
          Categories=Application;
        mode: '0775'
        dest: ~/.local/share/applications/1Password.desktop

  when: "not '1password-cli' in ansible_facts.packages"
