---
- name: Install standard software for Ubuntu Desktop
  hosts: desktops

  tasks:
    - name:
      ansible.builtin.set_fact:
        my_user: "{{ lookup('ansible.builtin.env', 'USER')}}"

    - name: Ensure pre-reqs are installed
      ansible.builtin.apt:
        name:
          - software-properties-common
          - apt-transport-https
          - gnupg
      become: true

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Install the snap-store
      community.general.snap:
        name: snap-store
        state: present

    - name: Install application tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ apps }}"
      vars:
        apps:
          - 'vscode.yml'
          - '1password.yml'
          - 'docker.yml'
